### PR TITLE
Gizmo_UI_and_Raycasting

### PR DESCRIPTION
**Pull request by azer89**

### CODE REVIEW

**Comment by GodOfMemes** [comment]
You didn't include the folder for ImGuizmo. Also, it would probably be a good idea to remove all the VS2022 files since cmake can generate vs project files.

**Comment by azer89** [comment]
> You didn't include the folder for ImGuizmo. 

I have added ImGuizmo on .gitmodules

> Also, it would probably be a good idea to remove all the VS2022 files since cmake can generate vs project files.

Hmm... tbh I'm still not used to CMake so I want to keep VS files for now...

**Comment by GodOfMemes** [comment]
No not In cmake in the external folder, the folder for ImGuizmo isn't there

**Comment by azer89** [comment]
Oh I see the problem, Sourcetree didn't add the folder, I'm looking into it

**Pull request merged**
